// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqsksaGfmTNJ4cS2seW5JiV1l2RoVQVaM',
    appId: '1:397166996120:android:4f64a726d5ccab983cbeed',
    messagingSenderId: '397166996120',
    projectId: 'poc-innovation-iot',
    storageBucket: 'poc-innovation-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpxnLVnKqtAVc04PWiUtzim_xfZCA6qZ4',
    appId: '1:397166996120:ios:c8b49460fa0c247d3cbeed',
    messagingSenderId: '397166996120',
    projectId: 'poc-innovation-iot',
    storageBucket: 'poc-innovation-iot.appspot.com',
    androidClientId: '397166996120-0jv16tfo3oi8suk7kt7hce53gtcm57s9.apps.googleusercontent.com',
    iosClientId: '397166996120-bhm3jlr7dj13q1dd5qa220s7cehi08o0.apps.googleusercontent.com',
    iosBundleId: 'com.arise.starlight',
  );

}